name: doxygen
on:
  workflow_dispatch:
  pull_request:
  
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v4
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: .
        
      
            
