name: doxygen
on:
  workflow_dispatch:
  pull_request:
  
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v4
      - name: Install_Doxygen
        run: |
          mkdir doxygen
          cd doxygen
          wget https://www.doxygen.nl/files/doxygen-1.12.0.src.tar.gz
          gunzip doxygen-1.12.0.src.tar.gz
          tar xf doxygen-1.12.0.src.tar
      - name: check-current-dir
        run: ls -a
            
