name: Doxygen-GH Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get Doxygen
        run: |
          mkdir ../doxygen
          cd ../doxygen
          wget -q https://github.com/doxygen/doxygen/releases/download/Release_1_13_0/doxygen-1.13.0.linux.bin.tar.gz
          gunzip doxygen-1.13.0.linux.bin.tar.gz
          ls
