name: doxygen
on:
  workflow_dispatch:
  pull_request:
  
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - name: check-current-dir
        run: ls
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.8
            
